version: '3'

services:
    mariadb:
        container_name: Mariadb

        image: mariadb
        restart: unless-stopped

        volumes:
            - /home/mariadb:/var/lib/mysql

        environment:
            MARIADB_ROOT_PASSWORD: example



    wordpress:
        container_name: WordPress

        image: wordpress:apache
        restart: unless-stopped

        depends_on:
            - mariadb

        environment:
            WORDPRESS_DB_HOST: mariadb:3306
            WORDPRESS_DB_USER: wordpress_db_user
            WORDPRESS_DB_PASSWORD: zcl.123
            WORDPRESS_DB_NAME: wordpress_db

        volumes:
            - /home/wordpress:/var/www/html/wp-content

        ports:
            - '8080:80'
